---
title: "Model-Free Model Comparisons"
author: Brenden Eum
date: March 27, 2024
output: 
  html_document: 
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    code_folding: hide
    df_print: default
---

# Preamble

```{r}
# Libraries
rm(list=ls())
seed = 4
library(tidyverse)
library(brms)

# Directories
.datadir = file.path("/Users/brenden/Desktop/2023-gain-loss-attention/data/processed_data/datasets")
.tempdir = file.path("/Users/brenden/Desktop/2023-gain-loss-attention/analysis/outputs/temp/model_free_model_comparison")

# BRMS settings
cc = 3
iter = 6000
brm <- function(...)
  brms::brm(
    ...,
    iter = iter,
    warmup = floor(iter/2),
    chains = cc,
    cores = cc,
    seed = seed,
    refresh = F,
    file_refit = "on_change")

# Data
load(file.path(.datadir, "ecfr.RData"))
ecfr = ecfr[ecfr$firstFix==T,]
ecfr$oV = ecfr$vL + ecfr$vR

study1 = ecfr[ecfr$studyN==1,]
study2 = ecfr[ecfr$studyN==2,]
study1G = ecfr[ecfr$studyN==1 & ecfr$condition=="Gain",]
study2G = ecfr[ecfr$studyN==2 & ecfr$condition=="Gain",]
study1L = ecfr[ecfr$studyN==1 & ecfr$condition=="Loss",]
study2L = ecfr[ecfr$studyN==2 & ecfr$condition=="Loss",]
```

# rt ~ abs(vDiff) + oV

Control for high probabilities which might make the decision easier (faster).

## Study 1
You don't need to run this because raw and ref-dept oV are perfectly correlated in gains. oV = RoV+2. That being said, just run this as a replication of Smith and Krajbich (2019).
```{r}
print("Study 1G")
#lm(log(rt) ~ 1 + abs(vDiff) + oV, data=study1G) %>% summary()
# There is not enough variation in the effect of overall value between subjects. That means sd(oV) ends up being too small and the sampler goes crazy trying to figure out how to sample from it's posterior. It causes a bunch of divergent transitions and issues with low Effective Sample Size. As soon as you take out subject-level variation in the effect of overall value on log(rt), these problems go away. That's why I've opted to only include a population-level effect of overall value.
study1G_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff) + oV + (1 + abs(vDiff) | subject),
  data = study1G,
  family = gaussian(),
  prior = c(
    prior(normal(0,1.5), class=Intercept), 
    prior(normal(0,0.4), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study1G_rt_oV")
)
summary(study1G_rt_oV)

print("Study 1L")
#lm(log(rt) ~ 1 + abs(vDiff) + oV, data=study1L) %>% summary()
study1L_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff) + oV + (1 + abs(vDiff) | subject),
  data = study1L,
  family = gaussian(),
  prior = c(
    prior(normal(0,0.5), class=Intercept), 
    prior(normal(0,0.3), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study1L_rt_oV")
)
summary(study1L_rt_oV)
```
## Study 2
```{r}
print("Study 2G")
#lm(log(rt) ~ 1 + abs(vDiff) + oV, data=study2G) %>% summary()
# In Study 2, there was sufficient variation between subjects in the effect for overall value, so it was reintroduced back into the regression. This did not produce any errors or warnings like in Study 1.
study2G_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff) + oV + (1 + abs(vDiff) + oV | subject),
  data = study2G,
  family = gaussian(),
  prior = c(
    prior(normal(0,1.5), class=Intercept), 
    prior(normal(0,0.4), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study2G_rt_oV")
)
summary(study2G_rt_oV)

print("Study 2L")
#lm(log(rt) ~ 1 + abs(vDiff) + oV, data=study2L) %>% summary()
study2L_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff) + oV + (1 + abs(vDiff) + oV | subject),
  data = study2L,
  family = gaussian(),
  prior = c(
    prior(normal(0,0.5), class=Intercept), 
    prior(normal(0,0.3), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study2L_rt_oV")
)
summary(study2L_rt_oV)
```

# Do it by study

```{r}
print("Study 1")
# There is not enough variation in the effect of overall value between subjects. That means sd(oV) ends up being too small and the sampler goes crazy trying to figure out how to sample from it's posterior. It causes a bunch of divergent transitions and issues with low Effective Sample Size. As soon as you take out subject-level variation in the effect of overall value on log(rt), these problems go away. That's why I've opted to only include a population-level effect of overall value. My gut feeling is that this has something to do with the perceptual nature of the stimuli and how little variance there is in overall value. I feel like the combination of these two factors ends up meaning that people respond to the overall value effect in a similar manner. Not sure what more to do about it, but it's not really the focus of this paper or this analysis.
study1_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff)*relevel(condition,ref="Gain") + oV*relevel(condition,ref="Gain") + (1 + abs(vDiff)*relevel(condition,ref="Gain") | subject),
  data = study1,
  family = gaussian(),
  prior = c(
    prior(normal(0,1.5), class=Intercept), 
    prior(normal(0,0.4), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study1_rt_oV")
)
summary(study1_rt_oV)
```

```{r}
print("Study 2")
# In Study 2, there was sufficient variation between subjects in the effect for overall value, so it was reintroduced back into the regression. This did not produce any errors or warnings like in Study 1. I have a feeling it makes more sense to include subject-level variance in the overall value effect here because the stimuli are presented numerically and there's significantly more variance in the overall values that they are exposed to. This allows for a lot more heterogeneous response to the information presented on the screen than perceptual stimuli (which are already hard to distinguish), like in study 1.
study2_rt_oV = brm(
  log(rt) ~ 1 + abs(vDiff)*relevel(condition,ref="Gain") + oV*relevel(condition,ref="Gain") + (1 + abs(vDiff)*relevel(condition,ref="Gain") + oV*relevel(condition,ref="Gain") | subject),
  data = study2,
  family = gaussian(),
  prior = c(
    prior(normal(0,1.5), class=Intercept), 
    prior(normal(0,0.4), class="b", coef="absvDiff"),
    prior(normal(0,0.1), class="b", coef="oV")
  ),
  control = list(adapt_delta = 0.9),
  file = file.path(.tempdir, "Study2_rt_oV")
)
summary(study2_rt_oV)
```

